global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: production

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prompt-testing-lab-prod'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  - job_name: 'postgres-prod'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 60s

  - job_name: 'redis-prod'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 60s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s